In [104]:
import matplotlib.pyplot as py
import numpy as np
from sklearn import datasets, linear_model

In [105]:
diabetes = datasets.load_diabetes()

In [106]:
print(list(diabetes.keys()))

['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename']


In [107]:
diabetes_x = diabetes.data
diabetes_x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [108]:
diabetes_y = diabetes.target
diabetes_y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [109]:
diabetes_x.shape
#diabetes_y.shape


(442, 10)

In [110]:
diabetes_x_train = diabetes_x[:375,:]
diabetes_x_test = diabetes_x[375:,:]
diabetes_y_train = diabetes_y[:375]
diabetes_y_test = diabetes_y[375:]

In [111]:
model = linear_model.LinearRegression()

In [112]:
model.fit(diabetes_x_train,diabetes_y_train)
diabetes_y_test

array([217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69., 219.,
        72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,  43.,
       198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72., 140.,
       189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,  84.,
        42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,  94.,
       183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132., 220.,
        57.])

In [116]:
# example = model.predict[[0.03, 0.05, 0.07, 0.08, 0.09, 0.07, 0.06, 0.08, 0.09, 0.05]]
# print(example)

TypeError: 'method' object is not subscriptable

In [ ]:
diabetes_y_pred = model.predict(diabetes_x_test)

In [ ]:
from sklearn.metrics import mean_squared_error
a =  mean_squared_error(diabetes_y_test,diabetes_y_pred)
a

2640.4460532694693

In [ ]:
weight = model.coef_
intercept = model.intercept_
print("weights : ",weight)
print("intercept : ",intercept)

weights :  [  15.53636842 -264.85367326  526.12036098  303.07655341 -638.98015094
  353.38822701   20.43154649  135.21096384  662.57900763  126.62693388]
intercept :  152.71328318758884


In [117]:
import pandas as pd
df = pd.DataFrame({'Actual': diabetes_y_test, 'Predicted': diabetes_y_pred})
pd.set_option("display.max_rows", None, "display.max_columns", None)

print(df)
df

Actual   Predicted
0    217.0  177.597523
1    121.0  209.940542
2    235.0  163.295283
3    245.0  160.367890
4     40.0  141.671102
..     ...         ...
62   178.0  191.766975
63   104.0  104.464711
64   132.0  124.670132
65   220.0  208.949036
66    57.0   52.855483

[67 rows x 2 columns]