In [2]:
import pandas as pd
import numpy as np
df = pd.read_excel('insurance data.xlsx')
# print(df)

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(df[['age']],df.bought_insurance,train_size=0.8)

In [5]:
X_test

age
12   27
18   19
6    55
4    46
2    47
13   29

In [6]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [7]:
model.fit(X_train, y_train)

LogisticRegression()

In [8]:
y_predicted = model.predict(X_test)
print(y_predicted)

[0 0 1 1 1 0]


In [9]:
model.score(X_test,y_test)

0.8333333333333334

In [10]:
model.coef_

array([[0.15085102]])

In [11]:
model.intercept_

array([-5.4533363])

In [12]:
import math
def sigmoid(x):
  return 1 / (1 + math.exp(-x))
def prediction_function(age):
    z = 0.042 * age - 1.53 
    y = sigmoid(z)
    if y>0.5:
        y=1
    else:
        y=0
    return y

In [13]:
prediction_function(35)

0

In [14]:
prediction_function(43)

1